fixed_args:
    options:
        
        # Path to the dataset file
        "--data_path": "/home/listic/Bureau/cortes_stage/ML-WetSnowSAR_pipeline_stage/pipeline/data/dataset/dataset_AD_08200821_14Mas3Top3Phy_W15_corrected_V2.h5"
        
        # Method for the fold: simpleSplit, kFold, mFold, or combinationFold
        "--fold_method": "combinationFold"
        
        # Method for labeling: crocus, 3labels
        "--labeling_method": "crocus"
        
        # Method for resampling: bFold (can create more than 1000 folds, use with caution :D), oversample, undersample, or smote
        
        "--balancing_method": "undersample"
        
        # Filter request based on date and elevation criteria
        "--request": "(date.dt.month == 3 and date.dt.day == 1) and ((elevation > 1000) and (elevation < 2000))"
        
        # Shuffle the data before processing, shuffle uses the seed to reproduce the results
        "--shuffle_data": true
        
        # Balance the data
        "--balance_data": false
        
        # Import necessary libraries and modules
        "--import_list": 
            - "from sklearn.svm import SVC"
            - "from sklearn.neighbors import KNeighborsClassifier"
            - "from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier"
            - "from sklearn.linear_model import LogisticRegression"
            - "from sklearn.neural_network import MLPClassifier"
            - "from estimators.statistical_descriptor import *"
            - "from estimators.band_transform import *"
        
        # # Configuration for each pipeline
        # "--pipeline":
        # # KNeighborsClassifier pipeline
        #   - - - "KNN_direct"
        #     - - "BandSelector"
        #       - bands: [0,1,2,3,4,5,6,7,8]
        #     - - "BandTransformer"
        #       - bands : [0,1,2,3]
        #       - transformations : [] 
        #     - - "Hist_SAR"
        #     - - "KNeighborsClassifier"
        #       - n_neighbors: 50
        # #        - n_jobs: -1
        #   # RandomForestClassifier pipeline
        #   - - - "RandomForest_direct"
        #     - - "BandSelector"
        #       - bands: [0,1,2,3,4,5,6,7,8]
        #     - - "BandTransformer"
        #       - bands : [0,1,2,3]
        #       - transformations : [] 
        #     - - "Hist_SAR"
        #     - - "RandomForestClassifier"
        #       - n_estimators: 200
        #       - criterion: "entropy"
        # #        - n_jobs: -1
        #   # MLPClassifier pipeline
        #   - - - "MLP_direct"
        #     - - "BandSelector"
        #       - bands: [0,1,2,3,4,5,6,7,8]
        #     - - "BandTransformer"
        #       - bands : [0,1,2,3]
        #       - transformations : [] 
        #     - - "Hist_SAR"
        #     - - "MLPClassifier"
        #       - alpha: 0.01
        #   # SVC with RBF kernel pipeline
        #   - - - "SVMrbf_direct"
        #     - - "BandSelector"
        #       - bands: [0,1,2,3,4,5,6,7,8]
        #     - - "BandTransformer"
        #       - bands : [0,1,2,3]
        #       - transformations : [] 
        #     - - "Hist_SAR"
        #     - - "SVC"
        #       - kernel: "rbf"
        #       - probability: true
        #   # LogisticRegression pipeline
        #   - - - "LogisticR_direct"
        #     - - "BandSelector"
        #       - bands: [0,1,2,3,4,5,6,7,8]
        #     - - "BandTransformer"
        #       - bands : [0,1,2,3]
        #       - transformations : [] 
        #     - - "Hist_SAR"
        #     - - "LogisticRegression"
        #   # AdaBoostClassifier pipeline
        #   - - - "AdaBoost_direct"
        #     - - "BandSelector"
        #       - bands: [0,1,2,3,4,5,6,7,8]
        #     - - "BandTransformer"
        #       - bands : [0,1,2,3]
        #       - transformations : [] 
        #     - - "Hist_SAR"
        #     - - "AdaBoostClassifier"
        #       - n_estimators: 200   

        # Metrics to include in the final report
        "--metrics_to_report":
            - "f1_score_macro"
            - "f1_score_weighted"
            - "f1_score_multiclass"
            - "accuracy_score"
            - "precision_score_macro"
            - "recall_score_macro"
            - "roc_auc_score"
            - "log_loss"
            - "kappa_score"
            - "confusion_matrix"

varying_args:
    groups:
        - options:
            # Random seed for reproducibility
            "--seed": 100150
            "--pipeline":
            # KNeighborsClassifier pipeline
              - - - "KNN_direct"
                - - "BandSelector"
                  - bands: [0,1,2,3,4,5,6,7,8]
                - - "BandTransformer"
                  - bands : [0,1,2,3]
                  - transformations : [] 
                - - "Hist_SAR"
                - - "KNeighborsClassifier"
                  - n_neighbors: 50
            #        - n_jobs: -1   
            # LogisticRegression pipeline
              - - - "LogisticR_direct"
                - - "BandSelector"
                  - bands: [0,1,2,3,4,5,6,7,8]
                - - "BandTransformer"
                  - bands : [0,1,2,3]
                  - transformations : [] 
                - - "Hist_SAR"
                - - "LogisticRegression"
              # AdaBoostClassifier pipeline
              - - - "AdaBoost_direct"
                - - "BandSelector"
                  - bands: [0,1,2,3,4,5,6,7,8]
                - - "BandTransformer"
                  - bands : [0,1,2,3]
                  - transformations : [] 
                - - "Hist_SAR"
                - - "AdaBoostClassifier"
                  - n_estimators: 200       

        # - options:
        #     # Random seed for reproducibility
        #     "--seed": 100150
        #     "--pipeline":
              